version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase"
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -
      - sudo apt-get install -y nodejs
  pre_build:
    commands:
      - echo "Pre build phase"
  build:
    commands:
      - echo "Build phase"
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: .